### ISSUE TITLE
/f promote <player> and /f demote <player>

### ISSUE THREAD

**Issue by ghost** [magnusulf/Factions#13]
## Affected Plugin

- **Affected Plugin Name:** Factions
- **Affected Plugin Version:** 3.1.4

## Describe your Environment

- **Server Version:** Spigot 1.13.2

## Expected Results

Please give back the commands `/f promote <player>` or `/f demote <player>`. They are comfortable and short, for fast change of rank. And I do not even have to remember the names of the ranks or look for them.

**Comment by magnusulf** [comment]
As of right now I have no plans to do this but I am keeping the ticket open while I think about it.
