### ISSUE TITLE
/f powerBoost <set/add> <faction/player> <name> [amount=show]

### ISSUE THREAD

**Issue by ghost** [magnusulf/Factions#16]
It was good if the command `/f powerBoost` could add power not just set power. It will make it easier to add power without looking at how much the current bonus is. Allows you to add a bonus through another plugin.

Current command
`/f powerBoost <faction/player> <name> [amount=show]`

Suggested change add <set/add> parameter.
`/f powerBoost <set/add> <faction/player> <name> [amount=show]`

**Comment by magnusulf** [comment]
Have you considered doing this through code instead of commands? Is that possible to solve your problem?
I understand your wish, but I am also hesitant to making the plugin more complex.

**Comment by ghost** [comment]
A lot of plugins allow you to give rewards for mining, building, farming, killing, voting for the server, etc.
If the factions could easily add power bonus, /f powerBonus would be more usable. /f powerBoost is admin command, players can not access it on most servers. I do not think this modification would make the plugin more difficult.

**Comment by magnusulf** [comment]
> A lot of plugins allow you to give rewards for mining, building, farming, killing, voting for the server, etc.

Are those rewards usually given through commands?

**Comment by ghost** [comment]
Yes, many plugins allow it. In configuration will set the commands that will be triggered when the player finishes something. It would be good if I could simply add power as reward for something. 

It's just a proposal I have in my mind for a long time. 
https://github.com/MassiveCraft/Factions/issues/743
https://github.com/MassiveCraft/Factions/issues/1110

Otherwise, I think factions are good and there is no need to change them a lot.
