### ISSUE TITLE
/mstore/factions_faction/*.json -> sethome,home will not be renamed to setwarp,warp 

### ISSUE THREAD

**Issue by ghost** [magnusulf/Factions#22]
## Affected Plugin

- **Affected Plugin Name:** Factions
- **Affected Plugin Version:** 3.1.5

## Describe your Environment

- **Server Version:** 1.13.2

## Steps to Reproduce this Bug

After the update, perm are not renamed home,sethome -> warp,setwarp. Players have lost permission to use warps and create warps.

/mstore/factions_faction/*.json
```
    "home": [
      "ALLY",
      "19e8110f-7c1f-4745-acbf-8afb981023d1",
      "dd8ceb89-d139-46b5-aaec-b72c3bac7757",
      "5b0d61b3-de3e-4720-8300-f75d08c246c7",
      "affff123-6cd3-4f5b-a311-4cd99deceb53"
    ],
    "sethome": [
      "19e8110f-7c1f-4745-acbf-8afb981023d1",
      "dd8ceb89-d139-46b5-aaec-b72c3bac7757"
    ],
```

**Comment by magnusulf** [comment]
I am sorry. A fix is out on spigot as of a few hours ago.
