### ISSUE TITLE
Access : Change "Host Faction Allowed"

### ISSUE THREAD

**Issue by ghost** [magnusulf/Factions#32]
Hello, I'm using Factions 3.2.0 on Spigot 1.13.2.
Thank you for the rework of the Faction accesses, but one functionality that was previously available is now missing : I am not able to change the "Host Faction Allowed" value with the /f access command.

Step to reproduce : 
- Claim one chunk for your faction. By default, the "Host Faction allowed" that can be seen with `/f access view` is TRUE.
- In order to restrict the accesses to specific members only, I want to deny access to all the Faction using `/f access deny one MyFaction`. Before the rework, this was done by using `/f access f MyFaction false`.

Result : 
- In the chat, the following message is displayed : "Access at world 19 14 is already denied to your faction."
- The "Host Faction Allowed" is still true and all the members can still build/open chests etc (according to their rank).

Expected result : 
"Host Faction allowed" should be set to false, and no member of my faction should have access on the chunk.

**Comment by ghost** [comment]
Hello !
The fix for #40 commented the code that resolved this bug. Could this issue be reopened please ?

**Comment by baticag** [comment]
I second this problem, you fixed it and then reverted it...
