### ISSUE TITLE
ClaimsMustBeConnected Enforcement Option

### ISSUE THREAD

**Issue by BlipRanger** [magnusulf/Factions#35]
Hello! Just a quick feature request. Would it be possible to cause claims to be unclaimed if they become disconnected from the larger portion (home) of claims when "claimsMustBeConnected' are true? This could just be an option to prevent people from making islands of claims that are disconnected by claiming over to an area and then just unclaiming the chunks between.

**Comment by magnusulf** [comment]
Interesting feature. I am not closing this and it is definitely on the list of features I will consider adding but as always you are probably going to have to wait a while before it gets implemented.

**Comment by BlipRanger** [comment]
Sure, no problem! Just a requested feature on my server. I’ll actually start taking a look at the plugin code. I’d like to be able to assist in Factions3 at some point, so maybe I could branch and investigate adding this feature.

**Comment by magnusulf** [comment]
The implementation I have made does not unclaim land that is not connected to other land, but it forbids you from unclaiming if that would make it so the faction has to separate claims.
