### ISSUE TITLE
Server Crash after Claiming Chunk

### ISSUE THREAD

**Issue by halberfan** [magnusulf/Factions#38]
Always when someone wants to claim a chunk, the server crashes. Here's the error: 
https://pastebin.com/JGR6X9Lg

- I use the Economy Plugin "BagOfGold"
- Server Version is 1.14.2 (I know the Plugin isn't on 1.14.2 yet, but the owner updated it anyways, sorry)

**Comment by magnusulf** [comment]
Interesting, I am not sure how this can happen but I will try to investigate.

What you could do that might fix this for you is to run the command "/f moneyconvert" which should fix some issues with certain economy plugins. Note that doing this shouldn't cause any problems or be noticeable by players, but it can't be undone so please make a backup before you do in case something goes wrong.

**Comment by magnusulf** [comment]
Bump. Was it fixed?
