### ISSUE TITLE
Problem with the Prefixes

### ISSUE THREAD

**Issue by nilsrob1** [magnusulf/Factions#4]
Hey I just downloaded your plugin and the prefixes seems to be not working for me for some reason, Im running 1.13.2. and this is my prefix in the config file:
"chatSetFormatTo": "<{factions_relcolor}§l{factions_roleprefix}§r{factions_relcolor}{factions_name|rp}§f%1$s> %2$s",

And it looks like that ingame aswell.

**Comment by magnusulf** [comment]
Do you have an error like this on startup?

https://pastebin.com/pQc9Usvp

**Comment by nilsrob1** [comment]
I think I found another plugin that works but thanks! and it was no errors, just the prefixes didnt work.
