### ISSUE TITLE
Elevated access on normal claims

### ISSUE THREAD

**Issue by ghost** [magnusulf/Factions#40]
## Affected Plugin

- **Affected Plugin Name:** Factions
- **Affected Plugin Version:** 3.2.2

## Describe your Environment

- **Server Version:** Spigot 1.13.2 "final build"
- Blank server, no other plugins than Factions & MassiveCore

## Steps to Reproduce this Bug

1. While being in a rank that doesn't have the permission to build, try to build in your Faction's land.

## Observed Results

The build is not denied as it should be.

## Additional information
The bug does NOT happen on 3.2.0. It is very probably related to the fact that, when entering our own claim, the message "You have elevated access to that area" appear although no custom accesses have been set.
Given those two information, I suppose the bug is related to the fix of #32.

Thank you.

**Comment by Seasonull** [comment]
I can second this, mostly.  Having the same issue, didn't do any testing.
