### ISSUE TITLE
Forced autocomplete on Faction name

### ISSUE THREAD

**Issue by ghost** [magnusulf/Factions#41]
## Affected Plugin

- **Affected Plugin Name:** Factions
- **Affected Plugin Version:** 3.2.2

## Describe your Environment

- **Server Version:** Spigot 1.13.2 "final build"
- Blank server, no other plugins than Factions & MassiveCore

## Steps to Reproduce this Bug

1. Create a Faction with a name that is a prefix of a rank or relation type (examples : "Truc" or "Memb")
2. From another Faction, try to set permission for the specific faction "Truc". (like with /f perm set build Truc yes)

## Observed Results
The command is executed as I typed "Truce" although I typed "Truc", so I cannot set specific permission for this Faction.

Thank you.

**Comment by ghost** [comment]
Oh, I just noticed that we can prefix the faction name with "faction-" like "/f perm set build faction-Truc yes", and it works as intended.
Feel free to close this issue as there is an easy workaround :)

**Comment by magnusulf** [comment]
Yeah, I am sorry this happens and it definitely shouldn't. But I added the prefix option exactly for situations like this so I am going to close this.
