### ISSUE TITLE
Empty factions don't dissappear

### ISSUE THREAD

**Issue by MithrandirCraft** [magnusulf/Factions#45]
## Affected Plugin
- **Affected Plugin Name:** Factions
- **Affected Plugin Version:** 3.2.0

## Describe your Environment
- **Server Version:** 1.13.2 (last build)

## Steps to Reproduce this Bug
No idea, you probably just have to have installed factions and let players build and abandon factions.

## Observed Results
Empty factions still remain once no players are left
![imagen](https://user-images.githubusercontent.com/6623704/61594633-58afe780-abee-11e9-8f56-a16050b09ad8.png)

## Expected Results
Factions should dissapear once players are expelled for inactivity. This may have been fixed in Factions3, but I still feel like it should be reported.

For now I'll just delete them and see if more get accumulated.

**Comment by magnusulf** [comment]
Did more Factions accumulate?

**Comment by MithrandirCraft** [comment]
No.

**Comment by magnusulf** [comment]
Then I'll assume it was a one-time bug that is difficult to reproduce and not worth trying to fix.

**Comment by MithrandirCraft** [comment]
I'll reopen if it re-emerges.
