### ISSUE TITLE
Faction Boat/Vehicle Perms

### ISSUE THREAD

**Issue by Aeyori** [magnusulf/Factions#46]
## Affected Plugin

- **Affected Plugin Name:** Factions
- **Affected Plugin Version:** 3.2.2

## Describe your Environment

- **Server Version:**  
1.14.4

## Steps to Reproduce this Bug

Tried looking up faction perms on wiki
Used ingame commands to view perms
Tried to create permission yml but didn't work

## Observed Results
No permission to allow boat placing in safezone. I have players start out on an island with a boat but they can't place it down in water cause it's in safezone and apparently there's no permission to allow boat placing. I saw that the console says I can't place vehicles down. 

## Expected Results

I expect there to be a permission that allows boat placing in SafeZone.

**Comment by magnusulf** [comment]
I just tested this and it seems everyone can place boats everywhere and AFAIK there is no place in the Factions source code that blocks people from placing boats.

Can you elaborate on what you want?

**Comment by Aeyori** [comment]
Yes, there is no problem with placing a boat in the wilderness, however players cannot place boats inside a SafeZone. Whenever they try to place a boat into the SafeZone, it says they are not allowed to use vehicles in that area.

**Comment by magnusulf** [comment]
What exactly is the error message?

**Comment by Aeyori** [comment]
Hey! Sorry, but you can't place vehicles here. 

After further realization I believe it is not a Factions problem. I made a SafeZone away from spawn (Don't know why I didn't think of this before) and I could place boats. So I think it's definitely a spawn problem. Sorry for the wrong claim and if you have any knowledge on what plugin could be causing this then that would be great! Thank you!

**Comment by magnusulf** [comment]
That message sounds like WorldGuard so you probably have a WorldGuard region protecting the place.
