### ISSUE TITLE
Factions do not save player names 

### ISSUE THREAD

**Issue by ghost** [magnusulf/Factions#48]
Players are stored only under id. After restarting the server, I cannot use player names in commands until the player logs in again.

**Comment by magnusulf** [comment]
Do you have a file at server/plugins/MassiveCore/idnamecache.json ? There is supposed to be a file there with names and ids.

**Comment by ghost** [comment]
Oh, I was looking for it in ~/mstore/... There are only a few players in idnamecache, can something reset idnamecache? I do not understand why so few players are stored there.

**Comment by magnusulf** [comment]
Do you still experience this problem. I have absolutely no clue what is causing it or how to fix it.

**Comment by ghost** [comment]
I don't know what caused it. Hopefully it won't happen again.
