### ISSUE TITLE
/f rank /f warp commands do not work

### ISSUE THREAD

**Issue by ghost** [magnusulf/Factions#5]
## Affected Plugin

- **Affected Plugin Name:** Factions
- **Affected Plugin Version:** 3.1.1

## Describe your Environment

- **Server Version:** Spigot 1.13.2

## Steps to Reproduce this Bug

New commands /f warp /f perm are not in the menu and do not work. 

/mstore/factions_mconf/instance.json
`"warpsEnabled": true,`

**Comment by magnusulf** [comment]
I believe this and #6 is fixed in the just released version 3.1.2. Sorry for the inconvenience.

Please tell me whether or not they are fixed.

**Comment by ghost** [comment]
It is fixed, but i have some notes :-)

1.  Is it a good `/f warp list`? What does **b** mean?
![image](https://user-images.githubusercontent.com/9903203/52531901-d22cdb00-2d1c-11e9-8882-b201d735f7dd.png)

2. Command `/f warp go <warp>` will often be used. Shorter command would be better, like `/f w <warp>`. Similar to `/f faction` -> `/f f`

3. It was good to promote players using `/f promote <player>` or `/f demote <player>`. Now it is not possible and I have to write `/f rank set <player> <rank>`.

**Comment by magnusulf** [comment]
> 2. Command `/f warp go <warp>` will often be used. Shorter command would be better, like `/f w <warp>`. Similar to `/f faction` -> `/f f`

I will consider it. Also you can do "/f wa g <warpName>"

> 3. It was good to promote players using `/f promote <player>` or `/f demote <player>`. Now it is not possible and I have to write `/f rank set <player> <rank>`.

This is actually intentional, to avoid giving people a wrong rank. Was it wrong to remove it? Perhaps, but I hope you at least understand why.
