### ISSUE TITLE
Raids in a faction where monsters are off.

### ISSUE THREAD

**Issue by ghost** [magnusulf/Factions#50]
Factions 3.2.3
Spigot 1.14.4

Raids in a faction where monsters are off. Illager can not hurt players, but annoy.

**Comment by magnusulf** [comment]
Does this also apply to illagers when there is no raid?

**Comment by ghost** [comment]
Yes, they also attack players. In a safe zone, illagers should not spawn.

**Comment by magnusulf** [comment]
Fixed in e7dc6bd
