### ISSUE TITLE
Factions claims doesn't save at all

### ISSUE THREAD

**Issue by alaajel** [magnusulf/Factions#54]
## Affected Plugin

- **Affected Plugin Name:** Factions
- **Affected Plugin Version:** latest
![image](https://user-images.githubusercontent.com/34905970/63684004-f3fb3480-c80c-11e9-89d4-cee6d9ef516a.png)

## Describe your Environment

- **Server Version:** ???
![image](https://user-images.githubusercontent.com/34905970/63684023-ff4e6000-c80c-11e9-8576-077226486383.png)

## Steps to Reproduce this Bug

1. Make a faction
2. claim a land
3. restart the server

## Observed Results

there we go claimed land gone
it should be saved but nope

**Comment by alaajel** [comment]
appeartnly storing worlds in like this

Worlds/Build1
deletes file that saves land

**Comment by magnusulf** [comment]
Have you tried to reproduce this bug on a server that has only Factions and MassiveCore?

I need more info to know how to reproduce and fix this.

**Comment by alaajel** [comment]
Yes it does the same but only storing thr world like this folder inside a folder worlds/build1

**Comment by magnusulf** [comment]
I just tested with the world-container setting set so the worlds would be saved in a folder. It works I am not sure why yours don't but I'll need more information in order to fix it.

**Comment by alaajel** [comment]
Did you test on linux?

**Comment by magnusulf** [comment]
No I did not. I tested in on macOS but I really doubt the OS makes a difference here but if you've made tests that says otherwise please tell me

**Comment by alaajel** [comment]
Okay i will report when i get time
