### ISSUE TITLE
(1.14.4) Lecturns

### ISSUE THREAD

**Issue by Midnight9746** [magnusulf/Factions#55]
## Affected Plugin
Factions

## Describe your Environment
Using 1.14.4 items

## Steps to Reproduce this Bug
Placed a lectern and other 1.14.4 items in the faction claim, then players who aren't in the faction are able to use them such as taking books from lecterns.

## Observed Results
Players (in the faction or not) can take books from lecterns and use other 1.14.4 blocks

## Expected Results
They must be in the faction with permission to use that block.

**Comment by magnusulf** [comment]
What other blocks than lecterns does this apply to?

**Comment by magnusulf** [comment]
Was fixed in da97ad1
