### ISSUE TITLE
Default settings (1.14.3)

### ISSUE THREAD

**Issue by Artakia** [magnusulf/Factions#56]
Im trying to change the default settings of the factions.
For example: I tried to change the people, who have access to the faction containers by default.
(I wanted them to be accessable by everyone by default)
I changed the default container file to this:
{
  "version": 1,
  "priority": 6000,
  "name": "container",
  "desc": "use containers",
  "standard": [
    "LEADER",
    "OFFICER",
    "MEMBER",
    "RECRUIT",
    "ALLY",
    "TRUCE",
    "NEUTRAL",
    "ENEMY"
  ],
  "territory": true,
  "editable": true,
  "visible": true
}

When I save the file, the console said: 

07.09 10:15:14 [Server] Server thread/INFO [MassiveCore 3.2.3] Error: Raw data was null. Is the file completely empty?
07.09 10:15:14 [Server] Server thread/INFO [MassiveCore 3.2.3] Collection: Factions::factions_mperm
07.09 10:15:14 [Server] Server thread/INFO [MassiveCore 3.2.3] Entity: container
07.09 10:15:14 [Server] Server thread/INFO [MassiveCore 3.2.3] Database could not load entity. You edited a file manually and made wrong JSON

Is there a way to edit the default settings at all?

**Comment by jonahJS** [comment]
Hi, I would like to know this too!

**Comment by magnusulf** [comment]
I am going to need more info. I copy pasted your configuration onto my test server and it loaded like expected. It also behaved like expected with everyone having access per default.

**Comment by Artakia** [comment]
Since I played with the default configs, after posting this issue, I just tried it again:

I pasted my config file from above to the container.json (https://pastebin.com/JLPnp55c)
After saving it, the server console says the following 4 lines: https://pastebin.com/kf5tvzeD

I cant manage to fix this.

**Comment by magnusulf** [comment]
Have you manage to change any of the other permissions without errors?

**Comment by Artakia** [comment]
No, I tried the same on doors, buttons an some others, but I'm always getting the error

**Comment by magnusulf** [comment]
Sorry for not responding earlier. This is clearly an error with your database for some reason the server can't properly read it when you edit files manually I am not sure I know how to help with that.
