### ISSUE TITLE
"Faction Economy Features are disabled"

### ISSUE THREAD

**Issue by ItzDoughTime** [magnusulf/Factions#58]
## Affected Plugin

- **Affected Plugin Name:** Factions
- **Affected Plugin Version:** 3.2.3

## Describe your Environment

- **Server Version:** 1.14.0

## Steps to Reproduce this Bug

1. typed /f money in chat
2.  Chat reads "Faction Economy Features Are Disabled"

**Comment by magnusulf** [comment]
Have you set "econEnabled" to true in the config?
Do you have an economy plugin and Vault installed?

**Comment by magnusulf** [comment]
Closed. Inactive.
