### ISSUE TITLE
Money Deposit Bug

### ISSUE THREAD

**Issue by JenkoRun** [magnusulf/Factions#59]
## Affected Plugin

- **Affected Plugin Name:** Factions
- **Affected Plugin Version:** 3.2.3

## Describe your Environment

- **Server Version:** git-paper-209

## Steps to Reproduce this Bug

1. Create a faction.
2. Try to deposit any amount into the faction balance.
3. Internal error in chat and this error in the log:

05.10 07:49:03 [Server] ERROR null
05.10 07:49:03 [Server] INFO org.bukkit.command.CommandException: Unhandled exception executing 'f money deposit 50 test' in com.massivecraft.massivecore.command.MassiveCoreBukkitCommand(f)
05.10 07:49:03 [Server] INFO at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:169) ~[patched_1.14.4.jar:git-Paper-209]
05.10 07:49:03 [Server] INFO at org.bukkit.craftbukkit.v1_14_R1.CraftServer.dispatchCommand(CraftServer.java:739) ~[patched_1.14.4.jar:git-Paper-209]
05.10 07:49:03 [Server] INFO at net.minecraft.server.v1_14_R1.PlayerConnection.handleCommand(PlayerConnection.java:1800) ~[patched_1.14.4.jar:git-Paper-209]
05.10 07:49:03 [Server] INFO at net.minecraft.server.v1_14_R1.PlayerConnection.a(PlayerConnection.java:1608) ~[patched_1.14.4.jar:git-Paper-209]
05.10 07:49:03 [Server] INFO at net.minecraft.server.v1_14_R1.PacketPlayInChat.a(PacketPlayInChat.java:47) ~[patched_1.14.4.jar:git-Paper-209]
05.10 07:49:03 [Server] INFO at net.minecraft.server.v1_14_R1.PacketPlayInChat.a(PacketPlayInChat.java:5) ~[patched_1.14.4.jar:git-Paper-209]
05.10 07:49:03 [Server] INFO at net.minecraft.server.v1_14_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:23) ~[patched_1.14.4.jar:git-Paper-209]
05.10 07:49:03 [Server] INFO at net.minecraft.server.v1_14_R1.TickTask.run(SourceFile:18) ~[patched_1.14.4.jar:git-Paper-209]
05.10 07:49:03 [Server] INFO at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.14.4.jar:git-Paper-209]
05.10 07:49:03 [Server] INFO at net.minecraft.server.v1_14_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.14.4.jar:git-Paper-209]
05.10 07:49:03 [Server] INFO at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.14.4.jar:git-Paper-209]
05.10 07:49:03 [Server] INFO at net.minecraft.server.v1_14_R1.MinecraftServer.aX(MinecraftServer.java:1029) ~[patched_1.14.4.jar:git-Paper-209]
05.10 07:49:03 [Server] INFO at net.minecraft.server.v1_14_R1.MinecraftServer.executeNext(MinecraftServer.java:1022) ~[patched_1.14.4.jar:git-Paper-209]
05.10 07:49:03 [Server] INFO at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[patched_1.14.4.jar:git-Paper-209]
05.10 07:49:03 [Server] INFO at net.minecraft.server.v1_14_R1.MinecraftServer.sleepForTick(MinecraftServer.java:1006) ~[patched_1.14.4.jar:git-Paper-209]
05.10 07:49:03 [Server] INFO at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:929) ~[patched_1.14.4.jar:git-Paper-209]
05.10 07:49:03 [Server] INFO at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]
05.10 07:49:03 [Server] INFO Caused by: java.lang.RuntimeException
05.10 07:49:03 [Server] INFO at com.massivecraft.massivecore.money.MoneyMixinVault.move(MoneyMixinVault.java:219) ~[?:?]
05.10 07:49:03 [Server] INFO at com.massivecraft.massivecore.money.MoneyMixinAbstract.move(MoneyMixinAbstract.java:64) ~[?:?]
05.10 07:49:03 [Server] INFO at com.massivecraft.massivecore.money.Money.move(Money.java:146) ~[?:?]
05.10 07:49:03 [Server] INFO at com.massivecraft.factions.integration.Econ.moveMoney(Econ.java:307) ~[?:?]
05.10 07:49:03 [Server] INFO at com.massivecraft.factions.integration.Econ.moveMoney(Econ.java:296) ~[?:?]
05.10 07:49:03 [Server] INFO at com.massivecraft.factions.integration.Econ.transferMoney(Econ.java:142) ~[?:?]
05.10 07:49:03 [Server] INFO at com.massivecraft.factions.integration.Econ.transferMoney(Econ.java:101) ~[?:?]
05.10 07:49:03 [Server] INFO at com.massivecraft.factions.cmd.CmdFactionsMoneyDeposit.perform(CmdFactionsMoneyDeposit.java:42) ~[?:?]
05.10 07:49:03 [Server] INFO at com.massivecraft.massivecore.command.MassiveCommand.execute(MassiveCommand.java:1176) ~[?:?]
05.10 07:49:03 [Server] INFO at com.massivecraft.massivecore.command.MassiveCommand.execute(MassiveCommand.java:1132) ~[?:?]
05.10 07:49:03 [Server] INFO at com.massivecraft.massivecore.command.MassiveCommand.execute(MassiveCommand.java:1132) ~[?:?]
05.10 07:49:03 [Server] INFO at com.massivecraft.massivecore.command.MassiveCoreBukkitCommand.execute(MassiveCoreBukkitCommand.java:60) ~[?:?]
05.10 07:49:03 [Server] INFO at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159) ~[patched_1.14.4.jar:git-Paper-209]
05.10 07:49:03 [Server] INFO ... 16 more 

This makes it impossible for regular players to claim faction land. Also, no Factions folder is generated, leaving me unable to modify the town prices.

**Comment by magnusulf** [comment]
Try to do "/f moneyconvert" from the console. That probably fixes your problem.

**Comment by magnusulf** [comment]
Closed. Inactive.
