### ISSUE TITLE
Faction Money is Broken

### ISSUE THREAD

**Issue by Aeyori** [magnusulf/Factions#60]
## Affected Plugin

- **Affected Plugin Name:** Factions
- **Affected Plugin Version:** 3.2.3

## Describe your Environment

- **Server Version:** 
Paper 1.14.4
Factions 3.2.3

## Steps to Reproduce this Bug

I created a faction and tried using the /f money deposit
but when i did it gave an error in console 
## Observed Results

Error in console when doing /f money deposit <amount> 
https://pastebin.com/HHdTz0f0
## Expected Results

Money is supposed to be deposited to faction

**Comment by magnusulf** [comment]
Try to do "/f moneyconvert" from the console. That probably fixes your problem.

**Comment by Aeyori** [comment]
That was the fix! Thank you! I did this a long time ago but never thanked you, so sorry for the late reply!
