### ISSUE TITLE
Faction Money Disappearing

### ISSUE THREAD

**Issue by Aeyori** [magnusulf/Factions#67]
## Affected Plugin

- **Affected Plugin Name:** Factions
- **Affected Plugin Version:** 3.2.3

## Describe your Environment

- **Server Version:**  Paper 1.14.4

## Steps to Reproduce this Bug

I have not tried anything yet besides looking through configs and logs. I have not seen an error. Player reported issue:
Faction money keeps resetting to 0, nothing in town money either to see if thats where it went.

## Observed Results

Faction money keeps resetting to 0. 

## Expected Results

Money is not supposed to reset to 0.

**Comment by MithrandirCraft** [comment]
+1, this happens on my server too.

MC: 1.13.2
I'm currently using Paper, but this issue was present when I was using Spigot.
Factions3: 3.2.3

I have no idea when exactly this occurs, but I can guarantee it's not during a restart.

**Comment by magnusulf** [comment]
It is probably an incompatibility between factions and you economy plugin. Try doing "/f moneyconvert" and see if that fixes the problem. Please report back and tell me if it did.
