### ISSUE TITLE
Not enough power when at max.

### ISSUE THREAD

**Issue by BlankDot** [magnusulf/Factions#68]
## Affected Plugin
- **Affected Plugin Name:** Factions
- **Affected Plugin Version:** 3.2.3

## Describe your Environment

- **Server Version:** 1.14.4 Spigot

## Steps to Reproduce this Bug
I've claimed a total of 101 chunks and want to claim more, I'm sitting at the edited max power (100) and every time I try to claim more land the error for a lack of power pops up. I'm unsure if other players are experiencing this.

## Observed Results
Faction can't claim anymore land.

## Expected Results
I should be able to claim land even if it's one chunk at a time, I took a look at the config and unless I'm blind I couldn't see anything setting the required value of power needed to claim land. I looked in the factions and the massivecore config files.

**Comment by magnusulf** [comment]
If you have 100 power you should only be able to claim 100 chunks. You can edit the max power,  the min power, how fast power is regenerated, how much is lost upon death, and other settings regarding power but the plugin works as intented you shouldn't be able to claim chunks when you have claimed more than you have power.
