### ISSUE TITLE
Latest Push is Newer than Download

### ISSUE THREAD

**Issue by blitzfall** [magnusulf/Factions#69]
The latest push claims to have added support for Factions Dynmap however the JAR download is older and still doesn't have this latest push. Is there any way for me to compile your latest push or update my existing Factions.jar file?

**Comment by magnusulf** [comment]
Of course the latest push is newer than the downloadable. Whenever I make a change it goes on GitHub first and then on Spigot later. You can just wait a little and I will publish a new version, probably within a week.

**Comment by blitzfall** [comment]
Thank you very much. I just wanted to make sure. Sorry if I came across as rude.

**Comment by magnusulf** [comment]
No you didn't. It's just good to know that changes goes on GitHub immediately and on Spigot every once in a while.

**Comment by blitzfall** [comment]
Wasn't the last update on Spigot back in August of 2019?

**Comment by TMCThomas** [comment]
> Wasn't the last update on Spigot back in August of 2019?

Yes but the plugin still works fine, so there was no necessity to update, plus he has a life aswell ;)
