### ISSUE TITLE
Tab Complete Warning Spam

### ISSUE THREAD

**Issue by tierrif** [magnusulf/Factions#70]
## Affected Plugin
- **Affected Plugin Name:** Factions
- **Affected Plugin Version:** 3.2.3

## Describe your Environment

- **Server Version:** Paper 652, Spigot 1.13.2 R0.1 SNAPSHOT

## Steps to Reproduce this Bug
1. Have an extremely high number of factions (around 150+)
2. Try to type down a command and let 1.13's autotab try to tablist factions
3. Get spammed by warnings like the one below in your chat

## Observed Results
![image](https://user-images.githubusercontent.com/44071180/72746751-d0b19700-3baa-11ea-8d25-0b75071e83d8.png)

## Expected Results
This is not particularly a bug, but it would be great if this were a setting. It becomes annoying to get spammed with these everytime.

**Comment by magnusulf** [comment]
The configuration you are asking for already exists. Go into the MassiveCore config and change the "tabCompletionLimit" to a higher number. Just be aware that a number too high can cause slow clients to lag and sometimes even case bandwith issues (although then you might need tens of thousands of entries, I am not exactly sure when that becomes a problem).
