### ISSUE TITLE
Factions Home/warp command

### ISSUE THREAD

**Issue by TMCThomas** [magnusulf/Factions#72]
Not really an issue or anything but more of a suggestion. 

The /f warp go <warpname>  command is maybe a bit lengthy to use. it's just not as convenient as /f home. maybe have both the warps and a home? It's ofcourse just a suggestion but me and some of my players would love the return of a quick factions home command. having to type the whole things out (and also forgetting to type "go" resulting in having to type it twice) is just a bit annoying. 

Greetings Thomas

**Comment by ghost** [comment]
i have the same problem with /f warp go name, i use commands.yml
```
aliases:
  w:
  - f warp go $1
```
/w "warp_name"

**Comment by magnusulf** [comment]
I have made it so that "/f home" is now equivalent to "/f warp go home". Will be included in next update.
