### ISSUE TITLE
economy is disabled but it is showing enabled whenever I enable it

### ISSUE THREAD

**Issue by santacodes** [magnusulf/Factions#73]
![Capture](https://user-images.githubusercontent.com/52504160/73138711-e41da000-408b-11ea-87ab-6d17829ea5ff.PNG)
![Capture](https://user-images.githubusercontent.com/52504160/73138718-f566ac80-408b-11ea-9485-6d1aea02ec17.PNG)

## Affected Plugin

- **Affected Plugin Name:** Factions
- **Affected Plugin Version:** ???

## Describe your Environment

- **Server Version:** ???

## Steps to Reproduce this Bug

1. First I did this.
2. Next I did that.
3. Finally this happened.

**Comment by magnusulf** [comment]
Do you have Vault and an economy plugin installed?

**Comment by santacodes** [comment]
Yes I have vault and essentialX installed

**Comment by GHOSTLYxKNIGHT** [comment]
im having this issue aswell. Vault is my only Econ plugin

**Comment by GHOSTLYxKNIGHT** [comment]
> im having this issue aswell. Vault is my only Econ plugin

Edit: I continued searching then found out i needed essentialsx or some other actual Economy plugin. still new to this tbh. After enabling EssentialsX and Vault i was able to do /f money with no errors :D
