### ISSUE TITLE
Maven repository for MassiveCore and Factions

### ISSUE THREAD

**Issue by eirikh1996** [magnusulf/Factions#74]
There should be created a Maven repository for Factions and MassiveCore

**Comment by PikaMug** [comment]
Agreed, or at least fix the MassiveSuper issue so we can compile with Jitpack.
https://jitpack.io/com/github/magnusulf/Factions/v2.13.6/build.log
https://jitpack.io/com/github/magnusulf/MassiveCore/-81bd0e6012-1/build.log

**Comment by SkytAsul** [comment]
Any news? It would be super handy to have a maven repo!
If you want, https://ci.codemc.io/ provides free CI and Nexus access (I use it to build my plugins, and @PikaMug as well I think).

**Comment by magnusulf** [comment]
I am sorry. This is not going to happen anytime soon. At this point I am mostly keeping this project alive for the few hundred servers that use it. I am not going to spend time figuring out how to do this for only a single small project
