### ISSUE TITLE
[QUESTION] Factions File Storage

### ISSUE THREAD

**Issue by PopcornMadness** [magnusulf/Factions#76]
Hi, quick question about Factions3 for 1.15.  Recently one of my players' factions completely disappeared.  I have a backup of the server, and was wondering where faction/claim files are stored.  Thanks!

**Comment by ghost** [comment]
I had the same problem, I do not know the solution https://github.com/magnusulf/Factions/issues/48

**Comment by magnusulf** [comment]
Closing this. I am sorry it happened to you but without more information I have no clue how to fix it. Unfortunately being the only developer and doing this as a side-project I do not have the time to investigate weird IO/database problems.
