### ISSUE TITLE
cant use /f sethome, says 

### ISSUE THREAD

**Issue by Backstabber010** [magnusulf/Factions#79]
when i try to do that ,it says, instead use this new command: /f warp........ I WANT F SETHOME PLEASEEEEEEEEEEEEEEEEEE

**Comment by alaajel** [comment]
you can make some sort of aliases /f sethome -> /f warp set home
and /f home -> /f warp go home

**Comment by magnusulf** [comment]
I have added /f home and /f sethome as aliases for /f warp go home and /f warp add home
