### ISSUE TITLE
Bad position /f map on

### ISSUE THREAD

**Issue by ghost** [magnusulf/Factions#8]
## Affected Plugin

- **Affected Plugin Name:** Factions
- **Affected Plugin Version:** 3.1.2

## Describe your Environment

- **Server Version:** Spigot 1.13.2

## Steps to Reproduce this Bug

Something wrong with `/f map on`, walking between chunks shows past position not current position on map.

**Comment by ghost** [comment]
The same problem as in 3.1.2 is also in 3.1.3. Chunk map is not fixed.

**Comment by magnusulf** [comment]
I fixed it after releasing 3.1.3. The patch will be in the next update 😄
