### ISSUE TITLE
LWC and Factions incompatibility (NPE during disabling)

### ISSUE THREAD

**Issue by JesFot** [magnusulf/Factions#88]
## Affected Plugin

- **Affected Plugin Name:** Factions
- **Affected Plugin Version:** 3.3.0

## Describe your Environment

- **Server Version:** 1.15.2

## Steps to Reproduce this Bug

1. Install Factions
2. Install LWCX
3. Start the server
4. Stop the server

## Observed Results
During shutdown, a NullPointerException is thrown from [EngineLWC, line 47](https://github.com/magnusulf/Factions/blob/7e5601462c6b57e722026967b7e0b0d26d9a7282/src/com/massivecraft/factions/integration/lwc/EngineLwc.java#L47) because LWC is disabled BEFORE Factions and so ``LWC.getInstance()`` returns null.

I already reported the issue at LWC [here](https://github.com/pop4959/LWCX/issues/106).

## Expected Results
Shutdown gracefully.

**Comment by magnusulf** [comment]
Would seem I fixed it back in december. It should be in the latest version. Please report back if it still occurs.
