### ISSUE TITLE
Not working with 1.16

### ISSUE THREAD

**Issue by TMCThomas** [magnusulf/Factions#90]
I'm not expecting anything soon or something like that. Just want to give you an heads up.

**Comment by uwelehmann** [comment]
> I'm not expecting anything soon or something like that. Just want to give you an heads up.

I see
> [21:53:28] [Server thread/ERROR]: Error occurred while enabling MassiveCore v3.3.0 (Is it up to date?)
in my logs - so I reported an Issue for "magnusulf / MassiveCore"

**Comment by BlipRanger** [comment]
Is this simply an issue with what versions the plugin is enabled for?

**Comment by TMCThomas** [comment]
> Is this simply an issue with what versions the plugin is enabled for?

Doubt it, it also doesn't seem to like that zombie pigmans are not a thing anymore.

**Comment by magnusulf** [comment]
I think I fixed that with the latest changes to MassiveCore. Will be published soon.

**Comment by TMCThomas** [comment]
any update on when it will be published?
