### ISSUE TITLE
[Request] disable leave faction if player have power in minus

### ISSUE THREAD

**Issue by XXX10Tacles** [magnusulf/Factions#95]
- **Affected Plugin Name:** Factions
well title says itself, i would like to see that feature cuz players are leaving faction if they die and go in minus.

**Comment by magnusulf** [comment]
Have you tried setting "canLeaveWithNegativePower" to false in the config?

This feature should already be supported.

**Comment by XXX10Tacles** [comment]
> Have you tried setting "canLeaveWithNegativePower" to false in the config?
> 
> This feature should already be supported.

oh no i didnot know that sry for wasting ur time and ty for info.
