### ISSUE TITLE
[Request] Add more faction home functionality, particularly regarding multi-home support and deleting homes

### ISSUE THREAD

**Issue by VoltroXP** [magnusulf/Factions#96]
## Affected Plugin

- **Affected Plugin Name:** Factions
- **Affected Plugin Version:** 3.3.2

## Describe your Environment

- **Server Version:** git-Paper-"1cda67118" (MC: 1.16.5)

## Current Functionality
The "/f home" command, or rather, alias, only supports having one home/warp. So, it's not even really an actual alias for the warp command. Also, "/f home" and "/f sethome" don't register as actual commands when they are typed, only showing their functionality/implementation when the commands are entered. There is also no delhome command.

## Proposed Changes
Add multi-home support, a delhome command, and register the commands so they can be tab-completed like every other command.

## Reason for Implementation
Other faction plugins have these, players and servers want it, and the current functionality and implementation is extremely bare bones.

**Comment by magnusulf** [comment]
Firstly, there is an unsethome command, but apparently you were too lazy to check that.

Secondly, as I've told you multiple times /f home is doing what it is intented: emulate the old behaviour. If you want to use multiple warps simply use /f warp, it is not that difficult.
